"""Pure renderers: answers -> `.env` / `.kamal/secrets` / README text.

Everything here is golden-testable: no I/O, no randomness (secrets come in).
"""

from saas_maker.secrets_gen import GeneratedSecrets
from saas_maker.wizard import Answers


def render_backend_env(a: Answers, s: GeneratedSecrets) -> str:
    """Local development `.env` for the backend (Mailpit for mail)."""
    return f"""# App
APP_NAME={a.name}
DEBUG=true

# Database
POSTGRES_HOST={a.pg_host}
POSTGRES_PORT={a.pg_port}
POSTGRES_USER={a.pg_user}
POSTGRES_PASSWORD={a.pg_password}
POSTGRES_DB={a.db_name}

# JWT Authentication (generated by saas-maker; rotate with: openssl rand -hex 32)
JWT_SECRET_KEY={s.jwt_secret}
JWT_ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=30
REFRESH_TOKEN_EXPIRE_DAYS=7

# Invitation System
INVITE_TOKEN_EXPIRE_DAYS=7
FRONTEND_URL=http://localhost:5190

# Email verification
EMAIL_VERIFICATION_TOKEN_EXPIRE_HOURS=48
REQUIRE_EMAIL_VERIFICATION=false

# Rate limiting on auth endpoints
RATE_LIMIT_ENABLED=true
RATE_LIMIT_AUTH=10/minute

# CORS
CORS_ORIGINS=http://localhost:5190,http://localhost:5191,http://localhost:3000
CORS_ALLOW_CREDENTIALS=true

# Email SMTP Configuration (local: Mailpit via docker compose, UI on :8025)
SMTP_HOST=localhost
SMTP_PORT=1025
SMTP_USER=
SMTP_PASSWORD=
SMTP_FROM_EMAIL={a.smtp_from}
SMTP_FROM_NAME={a.name}
SMTP_TLS=false
SMTP_SSL=false
"""


def render_vite_env() -> str:
    return "# API Base URL\nVITE_API_BASE_URL=http://localhost:8090\n"


def render_backend_secrets(a: Answers, s: GeneratedSecrets) -> str:
    """`backend/.kamal/secrets` — production values for Kamal (gitignored)."""
    return f"""# Docker Registry
DOCKER_REGISTRY_PASSWORD={a.docker_password}

# Database
POSTGRES_USER=postgres
POSTGRES_PASSWORD={a.pg_password}
POSTGRES_DB={a.db_name}

# JWT
JWT_SECRET_KEY={s.jwt_secret}

# Frontend URL (for invitation links)
FRONTEND_URL=https://{a.app_domain}

# SMTP Configuration
SMTP_HOST={a.smtp_host}
SMTP_PORT={a.smtp_port}
SMTP_USER={a.smtp_user}
SMTP_PASSWORD={a.smtp_password}
SMTP_FROM_EMAIL={a.smtp_from}
SMTP_FROM_NAME={a.name}
SMTP_TLS=true
SMTP_SSL=false
"""


def render_registry_secrets(a: Answers) -> str:
    """`frontend/.kamal/secrets` and `admin/.kamal/secrets`."""
    return f"# Docker Registry\nDOCKER_REGISTRY_PASSWORD={a.docker_password}\n"


def render_readme(a: Answers, ref: str) -> str:
    return f"""# {a.name}

Multi-tenant SaaS generated with [saas-maker](https://github.com/SaaS-Maker-Stack/saas-maker)
(`saas-maker new`, template `{ref}`).

| Path | Service | Run |
|------|---------|-----|
| `backend/` | FastAPI + SQLModel + PostgreSQL (API) | `make dev` (:8090) |
| `frontend/` | React + Vite — the tenant app | `npm run dev` (:5190) |
| `admin/` | React + Vite — platform admin panel | `npm run dev` (:5191) |

Each service is its own git repository, deployed independently with Kamal
(`config/deploy.yml`, secrets in `.kamal/secrets`). `DESIGN.md` is the design
system; `CLAUDE.md` files guide coding agents.

## Development

```bash
cd backend && make install && make migrate && make dev      # API on :8090 (docs at /docs)
cd frontend && npm install && npm run dev                    # app on :5190
cd admin && npm install && npm run dev                       # admin on :5191
```

Local mail goes to Mailpit (`docker compose up -d` starts Postgres + Mailpit,
UI on http://localhost:8025). Configuration lives in each service's `.env`.

## Quality

```bash
cd backend && make lint && make test && make audit
cd frontend && npm run lint && npm run typecheck && npm test && npm run audit
cd admin && npm run lint && npm run typecheck && npm test && npm run audit
```

## Adding a module

```bash
uvx saas-maker generate module invoice --label Factura --feminine \\
  --fields "number:str:Número,amount:float:Monto" --status "draft=Borrador,paid=Pagada"
```

Generates the tenant-scoped table, API, page, sidebar entry and tests on both
sides. Review the migration, then `cd backend && make migrate`.

## Production

| Service | URL |
|---------|-----|
| App | https://{a.app_domain} |
| Admin | https://{a.admin_domain} |
| API | https://{a.api_domain} |

```bash
cd backend && kamal deploy
cd frontend && kamal deploy
cd admin && kamal deploy
```
"""
